code-snippet/document-editor/es5-getting-started-cs1/js/index.html, code-snippet/document-editor/es5-getting-started-cs2/js/index.html
=> documentation(EJ2-71943): Fixed the sample issues

ej2-javascript/document-editor/js/getting-started.md, ej2-javascript/document-editor/ts/getting-started.md
=> documentation(830451): changed the code alignments

ej2-javascript/document-editor/ej2-javascript-document-editor-toc.html, ej2-javascript/document-editor/ej2-typescript-document-editor-toc.html, ej2-javascript/document-editor/index.md
Added overview content for Document Component
=> Added overview content for Document Component

ej2-javascript/code-snippet/document-editor/open-aws-s3/index.ts, ej2-javascript/code-snippet/document-editor/open-aws-s3/js/index.html, ej2-javascript/code-snippet/document-editor/open-aws-s3/systemjs.config.js, ej2-javascript/code-snippet/document-editor/open-aws-s3/ts/index.html, ej2-javascript/code-snippet/document-editor/save-aws-s3/index.ts, ej2-javascript/code-snippet/document-editor/save-aws-s3/js/index.html, ej2-javascript/code-snippet/document-editor/save-aws-s3/systemjs.config.js, ej2-javascript/code-snippet/document-editor/save-aws-s3/ts/index.html, ej2-javascript/document-editor/opening-documents/aws-s3-bucket.md, ej2-javascript/document-editor/opening-documents/azure-blob-storage.md, ej2-javascript/document-editor/saving-documents/aws-s3-bucket.md, ej2-javascript/document-editor/saving-documents/azure-blob-storage.md
Resolved the review correction for azure
=> UG(EJ2-835910): Resolved the review correction for azure

ej2-javascript/code-snippet/document-editor/open-aws-s3/index.ts, ej2-javascript/code-snippet/document-editor/open-aws-s3/js/index.html, ej2-javascript/code-snippet/document-editor/open-aws-s3/systemjs.config.js, ej2-javascript/code-snippet/document-editor/open-aws-s3/ts/index.html, ej2-javascript/code-snippet/document-editor/save-aws-s3/index.ts, ej2-javascript/code-snippet/document-editor/save-aws-s3/js/index.html, ej2-javascript/code-snippet/document-editor/save-aws-s3/systemjs.config.js, ej2-javascript/code-snippet/document-editor/save-aws-s3/ts/index.html, ej2-javascript/document-editor/ej2-javascript-document-editor-toc.html, ej2-javascript/document-editor/ej2-typescript-document-editor-toc.html, ej2-javascript/document-editor/opening-documents/aws-s3-bucket.md, ej2-javascript/document-editor/opening-documents/azure-blob-storage.md, ej2-javascript/document-editor/saving-documents/aws-s3-bucket.md, ej2-javascript/document-editor/saving-documents/azure-blob-storage.md
Added the UG for load/save documents from cloud
=> UG(EJ2-835910): Resolved the review correction

ej2-javascript/document-editor/js/getting-started.md, ej2-javascript/document-editor/ts/getting-started.md
Need to resolve the Page With Redirect - EJ2 docs links for document-editor documentation
Resolved the Page With Redirect - EJ2 docs links for document-editor documentation by adding the correct links
NA
No area is affected due to this changes.
NA
NA
* Did you run the automation against your implementation? NA
* Is there any API name change? No
* Is there any existing behavior change of other features due to this code change? No
* Does your new code introduce new warnings or binding errors? No
* Does your code pass all FxCop and StyleCop rules? Yes
* Did you record this case in the unit test or UI test? NA
=> documentation(839873): Add the correct path.

ej2-javascript/document-editor/table-format.md
**Description**
I have added UG documentation for title and description
=> feature(EJ2-846201): added UG for AltTab

README.md
**Description**
Ported updated Documentation User guide Details.
=> bug(849656):Ported updated Documentation User guide Details.

ej2-javascript/code-snippet/document-editor/getting-started-cs1/systemjs.config.js, ej2-javascript/document-editor/js/getting-started.md, ej2-javascript/document-editor/js/how-to/optimize-sfdt.md, ej2-javascript/document-editor/ts/getting-started.md, ej2-javascript/document-editor/ts/how-to/optimize-sfdt.md
Updated the getting started content
=> Updated the getting started content

ej2-javascript/document-editor/fields.md, ej2-javascript/document-editor/js/getting-started.md
Updated javascript getting started.
=> Updated javascript getting started.

ej2-javascript/code-snippet/document-editor/es5-getting-started-cs1/js/index.html, ej2-javascript/code-snippet/document-editor/es5-getting-started-cs2/js/index.html, ej2-javascript/document-editor/js/getting-started.md
=> Resolved the getting started issue.

ej2-javascript/code-snippet/document-editor/ruler-cs1/index.css, ej2-javascript/code-snippet/document-editor/ruler-cs1/index.js, ej2-javascript/code-snippet/document-editor/ruler-cs1/index.ts, ej2-javascript/code-snippet/document-editor/ruler-cs1/js/index.html, ej2-javascript/code-snippet/document-editor/ruler-cs1/systemjs.config.js, ej2-javascript/code-snippet/document-editor/ruler-cs1/ts/index.html, ej2-javascript/code-snippet/document-editor/ruler-cs2/index.css, ej2-javascript/code-snippet/document-editor/ruler-cs2/index.js, ej2-javascript/code-snippet/document-editor/ruler-cs2/index.ts, ej2-javascript/code-snippet/document-editor/ruler-cs2/js/index.html, ej2-javascript/code-snippet/document-editor/ruler-cs2/systemjs.config.js, ej2-javascript/code-snippet/document-editor/ruler-cs2/ts/index.html, ej2-javascript/document-editor/ej2-javascript-document-editor-toc.html, ej2-javascript/document-editor/ej2-typescript-document-editor-toc.html, ej2-javascript/document-editor/how-to/enable-ruler-in-document-editor-component.md
Description:
Ported ruler documentation.
=> feature(857019): Ruler Documentation hotfix.

ej2-javascript/code-snippet/document-editor/ruler-cs1/index.css, ej2-javascript/code-snippet/document-editor/ruler-cs1/index.js, ej2-javascript/code-snippet/document-editor/ruler-cs1/index.ts, ej2-javascript/code-snippet/document-editor/ruler-cs1/js/index.html, ej2-javascript/code-snippet/document-editor/ruler-cs1/systemjs.config.js, ej2-javascript/code-snippet/document-editor/ruler-cs1/ts/index.html, ej2-javascript/code-snippet/document-editor/ruler-cs2/index.css, ej2-javascript/code-snippet/document-editor/ruler-cs2/index.js, ej2-javascript/code-snippet/document-editor/ruler-cs2/index.ts, ej2-javascript/code-snippet/document-editor/ruler-cs2/js/index.html, ej2-javascript/code-snippet/document-editor/ruler-cs2/systemjs.config.js, ej2-javascript/code-snippet/document-editor/ruler-cs2/ts/index.html, ej2-javascript/document-editor/ej2-javascript-document-editor-toc.html, ej2-javascript/document-editor/ej2-typescript-document-editor-toc.html, ej2-javascript/document-editor/how-to/enable-ruler-in-document-editor-component.md
Description:
Ported ruler documentation.
=> feature(857019): Ruler Documentation.

ej2-javascript/document-editor/collaborative-editing.md, ej2-javascript/document-editor/ej2-javascript-document-editor-toc.html, ej2-javascript/document-editor/ej2-typescript-document-editor-toc.html
Added UG for collaborative editing
=> Added UG for collaborative editing

ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/index.js, ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/index.ts, ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/script-1.js, ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/script-1.ts, ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/script-2.js, ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/script-2.ts, ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/script-3.js, ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/script-3.ts, ej2-javascript/document-editor/collaborative-editing.md, ej2-javascript/document-editor/ej2-javascript-document-editor-toc.html, ej2-javascript/document-editor/ej2-typescript-document-editor-toc.html
Update Collaborative editing UG
=> feature(EJ2-861905): Update Collaborative editing UG

ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/index.js
Update instance name in UG documentation
=> 861905: Update Collaboration UG

ej2-javascript/code-snippet/document-editor/collaborative-editing-cs1/index.js
Update instance name in UG documentation
=> feature(EJ2-861905): Updated display text

ej2-javascript/document-editor/collaborative-editing.md
Resolved the toc issue and left-side content spinner issue.
=> Resolved the toc issue and left-side content spinner issue.

ej2-javascript/document-editor/collaborative-editing.md
Update UG for Collaborative Editing
=> feature(862893): Update collab UG

ej2-javascript/code-snippet/document-editor/open-aws-s3/index.ts, ej2-javascript/code-snippet/document-editor/open-aws-s3/js/index.html, ej2-javascript/code-snippet/document-editor/open-aws-s3/ts/index.html, ej2-javascript/code-snippet/document-editor/save-aws-s3/index.ts, ej2-javascript/code-snippet/document-editor/save-aws-s3/js/index.html, ej2-javascript/document-editor/ej2-javascript-document-editor-toc.html, ej2-javascript/document-editor/ej2-typescript-document-editor-toc.html, ej2-javascript/document-editor/opening-documents/aws-s3-bucket.md, ej2-javascript/document-editor/saving-documents/aws-s3-bucket.md
Added opening and saving in aws-s3-bucket
=> Added opening and saving in aws-s3-bucket

ej2-javascript/document-editor/web-services/core.md, ej2-javascript/document-editor/web-services/java.md
=> 861445: Updated Documentation

ej2-javascript/document-editor/saving-documents/azure-blob-storage.md
=> Resolved the publishing issue.

ej2-javascript/document-editor/accessibility.md
=> Added accessibility page.

ej2-javascript/document-editor/web-services/core.md, ej2-javascript/document-editor/web-services/java.md
861445: Updated feedback changes for tiff image
=> 861445: Updated feedback changes for tiff image

ej2-javascript/document-editor/accessibility.md
Need to modified the icons on accessibility document. The Icons are newly created for the compilance measuring.
[866555](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/866555)
NA
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Provide the details about the areas or combinations which have been tested against this code changes.
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes got approval if UI is …
=> 66555: Need to modified the icons on accessibility document

ej2-javascript/document-editor/paragraph-format.md
Hi @Aishwarya-Ganesan,
I have changed redirection links, please review.
Regards,
Scholar.
=> SEO-179238-Redirection-links

ej2-javascript/document-editor/image.md, ej2-javascript/document-editor/saving-documents/server-side-export.md, ej2-javascript/document-editor/spell-check.md
Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.
=> SEO-178901-ej2-js-documenteditor-redirect-links
